# Site
name: 'Mano Kapazoglou'
description: 'Some samples of my work'
logo: 'assets/images/logo.png'
baseurl: '/'
url: 'https://kapazoglou.info'
favicon: 'assets/images/logo.png'
avatar: 'assets/images/avatar.jpg'
email: 'mano@kapazoglou.info'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
